project:
    <ProjectName>
samples:
    <SampleName1>: /data/<SampleName1>
    <SampleName2>: /data/<SampleName2>
result_path:
    /results
SNV_filter_vaf:
    100
threads:
    7
genotype_filter:
    0
genotype_mapq:
    0
genotype_baseq:
    0
